// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAShvjL8RU0vyPfY9I2eehK8iaUGWpxdHg',
    appId: '1:767471836708:web:c38fa39f47c3006dea42b1',
    messagingSenderId: '767471836708',
    projectId: 'newproject-10bf1',
    authDomain: 'newproject-10bf1.firebaseapp.com',
    storageBucket: 'newproject-10bf1.appspot.com',
    measurementId: 'G-L2XYH9WJB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZxFKY8aX4Ov5eSbOky6041WyTqLkWMDo',
    appId: '1:767471836708:android:1b53c2e89f77446eea42b1',
    messagingSenderId: '767471836708',
    projectId: 'newproject-10bf1',
    storageBucket: 'newproject-10bf1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4sS2_P0WeH2UyKUVLtRqTwrWauPtpU1A',
    appId: '1:767471836708:ios:2a9564c9edc7c5d1ea42b1',
    messagingSenderId: '767471836708',
    projectId: 'newproject-10bf1',
    storageBucket: 'newproject-10bf1.appspot.com',
    iosBundleId: 'com.example.flutterApplication5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAShvjL8RU0vyPfY9I2eehK8iaUGWpxdHg',
    appId: '1:767471836708:web:350404b27ead1f3fea42b1',
    messagingSenderId: '767471836708',
    projectId: 'newproject-10bf1',
    authDomain: 'newproject-10bf1.firebaseapp.com',
    storageBucket: 'newproject-10bf1.appspot.com',
    measurementId: 'G-Z6VHELYWEX',
  );

}